name: Volo Monitor
on:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 mins
  workflow_dispatch:

jobs:
  check-volo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Cache
        uses: actions/download-artifact@v4
        with:
          name: game-cache
          path: .
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor
        run: python volo_monitor.py

      - name: Upload Cache
        uses: actions/upload-artifact@v4
        with:
          name: game-cache
          path: known_games.json
          retention-days: 7
